// OWL Turtle generator — converts ontology definitions to OWL Turtle format.
//
// Port of ontology_generator_manager.py from Ontos, simplified for TypeScript.
// Generates OWL Turtle format from class and property definitions.

import type { OwlClass, OwlProperty } from "@companygraph/shared/schema/ontology";

export interface OwlGeneratorOptions {
  baseIri: string;
  prefix?: string;
  includeComments?: boolean;
}

export class OwlGenerator {
  private baseIri: string;
  private prefix: string;
  private includeComments: boolean;

  constructor(options: OwlGeneratorOptions) {
    this.baseIri = options.baseIri;
    this.prefix = options.prefix || "cg";
    this.includeComments = options.includeComments ?? true;
  }

  generate(classes: OwlClass[], properties: OwlProperty[]): string {
    const lines: string[] = [];

    // Header
    lines.push("@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .");
    lines.push("@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .");
    lines.push("@prefix owl: <http://www.w3.org/2002/07/owl#> .");
    lines.push(`@prefix ${this.prefix}: <${this.baseIri}> .`);
    lines.push("");

    if (this.includeComments) {
      lines.push("# Ontology generated by CompanyGraph Ontology Generator");
      lines.push("");
    }

    // Ontology declaration
    lines.push(`@base <${this.baseIri}> .`);
    lines.push("");
    lines.push(`<> rdf:type owl:Ontology ;`);
    lines.push(`    rdfs:label "CompanyGraph Ontology" ;`);
    lines.push(`    rdfs:comment "Auto-generated ontology from CompanyGraph process landscape" .`);
    lines.push("");

    // Classes
    for (const cls of classes) {
      lines.push(this.generateClass(cls));
    }

    // Properties
    for (const prop of properties) {
      lines.push(this.generateProperty(prop));
    }

    return lines.join("\n");
  }

  private generateClass(cls: OwlClass): string {
    const lines: string[] = [];

    if (this.includeComments) {
      lines.push(`# Class: ${cls.label}`);
    }

    lines.push(`${this.prefix}:${this.localName(cls.iri)} rdf:type owl:Class ;`);

    if (cls.label) {
      lines.push(`    rdfs:label "${this.escapeString(cls.label)}" ;`);
    }

    if (cls.description) {
      lines.push(`    rdfs:comment "${this.escapeString(cls.description)}" ;`);
    }

    // Super classes
    if (cls.super_classes.length > 0) {
      const superClasses = cls.super_classes
        .map((iri) => `${this.prefix}:${this.localName(iri)}`)
        .join(" , ");
      lines.push(`    rdfs:subClassOf ${superClasses} ;`);
    }

    // Equivalent classes
    if (cls.equivalent_classes.length > 0) {
      const equivClasses = cls.equivalent_classes
        .map((iri) => `${this.prefix}:${this.localName(iri)}`)
        .join(" , ");
      lines.push(`    owl:equivalentClass ${equivClasses} ;`);
    }

    // Disjoint with
    if (cls.disjoint_with.length > 0) {
      const disjoint = cls.disjoint_with
        .map((iri) => `${this.prefix}:${this.localName(iri)}`)
        .join(" , ");
      lines.push(`    owl:disjointWith ${disjoint} ;`);
    }

    // Annotations
    if (cls.annotations) {
      for (const [key, value] of Object.entries(cls.annotations)) {
        lines.push(`    ${this.prefix}:${key} "${this.escapeString(value)}" ;`);
      }
    }

    // Remove trailing semicolon from last line
    const lastLine = lines[lines.length - 1];
    if (lastLine) {
      lines[lines.length - 1] = lastLine.replace(" ;", " .");
    }

    lines.push("");
    return lines.join("\n");
  }

  private generateProperty(prop: OwlProperty): string {
    const lines: string[] = [];

    if (this.includeComments) {
      lines.push(`# Property: ${prop.label}`);
    }

    const localName = this.localName(prop.iri);
    const rdfType = this.getPropertyType(prop.property_type);

    lines.push(`${this.prefix}:${localName} rdf:type ${rdfType} ;`);

    if (prop.label) {
      lines.push(`    rdfs:label "${this.escapeString(prop.label)}" ;`);
    }

    if (prop.description) {
      lines.push(`    rdfs:comment "${this.escapeString(prop.description)}" ;`);
    }

    // Domain
    if (prop.domain) {
      lines.push(`    rdfs:domain ${this.prefix}:${this.localName(prop.domain)} ;`);
    }

    // Range
    if (prop.range) {
      if (prop.property_type === "object") {
        lines.push(`    rdfs:range ${this.prefix}:${this.localName(prop.range)} ;`);
      } else {
        lines.push(`    rdfs:range ${prop.range} ;`);
      }
    }

    // Super properties
    if (prop.super_properties.length > 0) {
      const superProps = prop.super_properties
        .map((iri) => `${this.prefix}:${this.localName(iri)}`)
        .join(" , ");
      lines.push(`    rdfs:subPropertyOf ${superProps} ;`);
    }

    // Annotations
    if (prop.annotations) {
      for (const [key, value] of Object.entries(prop.annotations)) {
        lines.push(`    ${this.prefix}:${key} "${this.escapeString(value)}" ;`);
      }
    }

    // Remove trailing semicolon from last line
    const lastLine = lines[lines.length - 1];
    if (lastLine) {
      lines[lines.length - 1] = lastLine.replace(" ;", " .");
    }

    lines.push("");
    return lines.join("\n");
  }

  private getPropertyType(propertyType: string): string {
    switch (propertyType) {
      case "object":
        return "owl:ObjectProperty";
      case "data":
        return "owl:DatatypeProperty";
      case "annotation":
        return "owl:AnnotationProperty";
      default:
        return "owl:ObjectProperty";
    }
  }

  private localName(iri: string): string {
    // Extract local name from IRI
    const parts = iri.split(/[\/#]/);
    return parts[parts.length - 1] || iri;
  }

  private escapeString(str: string): string {
    return str
      .replace(/\\/g, "\\\\")
      .replace(/"/g, '\\"')
      .replace(/\n/g, "\\n")
      .replace(/\r/g, "\\r")
      .replace(/\t/g, "\\t");
  }
}

export function generateOwlTurtle(
  classes: OwlClass[],
  properties: OwlProperty[],
  options?: Partial<OwlGeneratorOptions>,
): string {
  const generator = new OwlGenerator({
    baseIri: options?.baseIri || "http://companygraph/ontology#",
    prefix: options?.prefix || "cg",
    includeComments: options?.includeComments ?? true,
  });
  return generator.generate(classes, properties);
}
